schema_version = "1.0.0"

id = "alternativa3d_tanki_format"
version = "1.0.0"
name = "Alternativa3D file format (Tanki Online HTML5)"
tagline = "Import-Export Alternativa3D 3D models used by Tanki Online HTML5"
maintainer = "Pyogenics <https://github.com/Pyogenics>"
type = "add-on"

website = "https://github.com/MapMakersAndProgrammers/io_scene_a3d"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:MIT",
]
copyright = [
   "2024 Pyogenics",
]

# wheels = [
# ]

[permissions]
files = "Import-Export Alternativa3D 3D model files"

# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]